# Generated by Django 6.0.2 on 2026-03-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(choices=[('classic', 'Classic Ivory'), ('ocean', 'Ocean Slate'), ('forest', 'Forest Mint'), ('custom', 'Custom')], default='classic', max_length=16)),
                ('color_primary', models.CharField(default='#0d0d12', max_length=7)),
                ('color_accent', models.CharField(default='#c9a84c', max_length=7)),
                ('color_background', models.CharField(default='#faf8f5', max_length=7)),
                ('color_surface', models.CharField(default='#f2eee7', max_length=7)),
                ('color_card', models.CharField(default='#fffcf7', max_length=7)),
                ('color_text', models.CharField(default='#2a2a35', max_length=7)),
                ('color_muted', models.CharField(default='#6c6c78', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
