# Generated by Django 6.0.2 on 2026-02-19 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('primary_job', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_label', models.CharField(blank=True, max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('role', models.CharField(blank=True, max_length=255)),
                ('is_closing', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='schedule.employee')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('employee', 'date', 'start_time')},
            },
        ),
    ]
